### ISSUE TITLE
Mismatched Exercises

### ISSUE THREAD

**Issue by joshmedeski** [makersquare/front-end-js-functions#1]
Hey Team,

I noticed the exercises in this repo don't align with the [lesson content](http://learn.makersquare.com/courses/frontend/week-3/javascript-functions-intro.lmd). Specifically "Exercise 1: My Life Line" (in the lesson) is different from "Exercise 1: tellFortune" (in the repo). These two items need to match.

I'm right in the middle of moving forward with the material so if someone else wants to fix this go ahead!

Otherwise I try and do it before I start the next course.

Thanks!

**Comment by gilbert** [comment]
You're right, most of these don't line up. @a17levine, are these perhaps two versions of the same things?

**Comment by a17levine** [comment]
@mindeavor @joshmedeski I think the exercises have diverged improperly. I think Sartaj originally wrote these and possibly were modified by Flip later on in a separate repo. I may have copied the repo that was not the most up-to-date. I may have time to fix it later today.
